---
title: "dataPrep.Rmd"
author: "Kaija Gahm"
date: "2022-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(move)
library(vultureUtils)
library(tidyverse)
library(feather) # for lightweight data storage
```

# Download initial data--2020 through present
```{r}
base::load("movebankCredentials/pw.Rda")
MB.LoginObject <- movebankLogin(username = 'kaijagahm', password = pw)
rm(pw)

dat <- vultureUtils::downloadVultures(loginObject = MB.LoginObject, removeDup = T, dfConvert = T, quiet = T, dateTimeStartUTC = "2020-01-01 00:00", dateTimeEndUTC = "2022-10-10 00:00")
write_feather(dat, "data/dat.feather")
dat <- read_feather("data/dat.feather")
```

Visualization: presence of vultures in the dataset over time.
```{r eval = FALSE}
# Let's look at the presence of the vultures over time.
unique(dat$trackId)
dates <- dat %>%
  dplyr::select(trackId, dateOnly) %>%
  distinct()

dates %>%
  ggplot(aes(x = trackId, y = dateOnly))+
  geom_point(size = 0.2)+
  coord_flip()
```

Now I'd like to annotate this data with periods to remove
```{r}
toRemove <- read.csv("data/whoswho_vultures04oct22_new.xlsx - periods_to_remove.csv")
head(toRemove)
toRemove <- toRemove %>%
  dplyr::select("trackId" = Movebank_id,
                remove_start,
                remove_end,
                reason) %>%
  mutate(across(c(remove_start, remove_end), .fns = function(x){
    lubridate::dmy(x)
  })) %>%
  dplyr::filter(!is.na(remove_end))

toRemove_long <- toRemove %>%
  group_by(trackId, reason) %>%
  # sequence of daily dates for each corresponding start, end elements
  dplyr::mutate(dateOnly = map2(remove_start, remove_end, seq, by = "1 day")) %>%
  # unnest the list column
  unnest(cols = c(dateOnly)) %>% 
  # remove any duplicate rows
  distinct() %>%
  dplyr::select(-c(remove_start, remove_end)) %>%
  rename("status" = reason)

# Join to the original data
datAnnot <- dat %>%
  left_join(toRemove_long, by = c("trackId", "dateOnly")) %>%
  mutate(status = replace_na(status, "valid"))
```

Visualize: presence over time, coloring by vulture status (i.e. whether or not to remove the data)
```{r eval = FALSE}
# Plot, coloring by the vulture status
datAnnot %>%
  dplyr::select(trackId, dateOnly, status) %>%
  distinct() %>%
  ggplot(aes(x = trackId, y = dateOnly, col = status))+
  geom_point(size = 0.2)+
  coord_flip()+
  guides(col = guide_legend(override.aes = list(size = 10)))+
  scale_color_viridis_d()

# Try again, just removing the invalid data.
datAnnot %>%
  filter(status == "valid") %>%
  dplyr::select(trackId, dateOnly) %>%
  distinct() %>%
  ggplot(aes(x = trackId, y = dateOnly))+
  geom_point(size = 0.2)+
  coord_flip()
```

Compute metrics for each vulture's presence in the data.
```{r}
# Now we can sort by a couple different things
## Compute start date, end date, and longest consecutive run.
metrics <- datAnnot %>%
  filter(status == "valid") %>%
  dplyr::select(trackId, dateOnly) %>%
  distinct() %>%
  group_by(trackId) %>%
  group_by(cumsum(c(0, diff(dateOnly) - 1))) %>%
  mutate(consecLen = n()) %>%
  ungroup() %>%
  group_by(trackId) %>%
  summarize(startDate = min(dateOnly),
            endDate = max(dateOnly),
            longestRun = max(consecLen))

datAnnot <- datAnnot %>%
  left_join(metrics, by = "trackId")

# Plot, sorting by earliest start date
datAnnot %>%
  filter(status == "valid") %>%
  mutate(trackId = forcats::fct_reorder(trackId, startDate, .desc = T)) %>%
  dplyr::select(trackId, dateOnly) %>%
  distinct() %>%
  ggplot(aes(x = trackId, y = dateOnly))+
  geom_point(size = 0.2)+
  coord_flip()

# Plot, sorting by earliest end date
datAnnot %>%
  filter(status == "valid") %>%
  mutate(trackId = forcats::fct_reorder(trackId, endDate, .desc = T)) %>%
  dplyr::select(trackId, dateOnly) %>%
  distinct() %>%
  ggplot(aes(x = trackId, y = dateOnly))+
  geom_point(size = 0.2)+
  coord_flip()

# Plot, sorting by longest run
datAnnot %>%
  filter(status == "valid") %>%
  mutate(trackId = forcats::fct_reorder(trackId, longestRun)) %>%
  dplyr::select(trackId, dateOnly) %>%
  distinct() %>%
  ggplot(aes(x = trackId, y = dateOnly))+
  geom_point(size = 0.2)+
  coord_flip()
```

Save the annotated dataset:
```{r}
write_feather(datAnnot, "data/datAnnot.feather")
```



